### ISSUE TITLE
Wrong Description of OccurenceOrderPlugin in Part 1

### ISSUE THREAD

**Issue by firejune** [AriaFallah/WebpackTutorial#16]
Hi.

While I was translated to Korean this tutorials I found small wrong description in part 1:
1. The `OccurenceOrderPlugin` is just reordering. It's not reduces to total file size. 
2. `OrderOccurencePlugin` is wrong word, `OccurenceOrderPlugin` is correct.

Thanks.

**Comment by AriaFallah** [comment]
Oh wow thanks for translating it!

As for your two points:
1. I copied the description from the official docs, and they said it reduces file size. Are they wrong? If they are I'll fix it.
2. Thanks for the catch! I got mixed up while writing it haha. It's fixed now.

**Comment by AriaFallah** [comment]
Going to close this for now. Let me know if I made any other mistakes!
