### ISSUE TITLE
loaders: ['raw-loader'] is also perfectly acceptable.

### ISSUE THREAD

**Issue by greemwahr** [AriaFallah/WebpackTutorial#22]
Using `loaders: "raw-loader''` is breaking when your run `webpack-dev-server --config webpack.config.dev.js`

**Comment by AriaFallah** [comment]
@shadowsyntax could you post the config that's screwing it up, and the part of the tutorial that's wrong?

**Comment by AriaFallah** [comment]
Hey I'm going to close this for now. Please if you can give more details, I'll reopen it.
