### ISSUE TITLE
Need style-loader on part1, example 4

### ISSUE THREAD

**Issue by bradleybossard** [AriaFallah/WebpackTutorial#23]
Awesome tutorial, super useful.

In part 1, example 4 on loaders, I believe you need to change

`npm install --save-dev css-loader`

to

`npm install --save-dev css-loader style-loader`

otherwise I get the error

`Module not found: Error: Cannot resolve module 'style'`

**Comment by AriaFallah** [comment]
Fixed here https://github.com/AriaFallah/WebpackTutorial/commit/6cb05c988d0ea8876a072427f21948486a74daa1

Thanks!
