### ISSUE TITLE
Integrate material from SurviveJS?

### ISSUE THREAD

**Issue by bebraw** [AriaFallah/WebpackTutorial#4]
Hi,

I've written a bit on the topic too. See [Webpack Compared](https://github.com/survivejs/webpack_react/blob/dev/manuscript/01_webpack_compared.md), [Developing with Webpack](https://github.com/survivejs/webpack_react/blob/dev/manuscript/02_developing_with_webpack.md), [Webpack and React](https://github.com/survivejs/webpack_react/blob/dev/manuscript/03_webpack_and_react.md), and [Building Kanban](https://github.com/survivejs/webpack_react/blob/dev/manuscript/08_building_kanban.md). Maybe you can integrate some of the ideas to your awesome guide.

**Comment by AriaFallah** [comment]
@bebraw I will definitely take a look! Thank you.
