### ISSUE TITLE
webpack 2 tutorial

### ISSUE THREAD

**Issue by hozefaj** [AriaFallah/WebpackTutorial#43]
Any chance of creating one for **webpack2**?

**Comment by AriaFallah** [comment]
I've been thinking updating this tutorial for a while, and while I've made improvements, I've never published them. The biggest problem right now is that I've moved away from web development mostly, and I don't wish to teach from a position of inexperience. So I'll probably never do it.

**Comment by hozefaj** [comment]
I would love to contribute here. Please do let me know if I can help. It will help me learn as well.

**Comment by AriaFallah** [comment]
I'm bad at deadlines, but the new tutorial is coming soon.
