### ISSUE TITLE
Using css/style loaders

### ISSUE THREAD

**Issue by wkoutre** [AriaFallah/WebpackTutorial#44]
BREAKING CHANGE:

It's no longer allowed to omit the '-loader' suffix when using loaders.
You need to specify 'style-loader' instead of 'style'.

Aside from that, this tutorial is wonderful. Thank you!

**Comment by AriaFallah** [comment]
@wkoutre yeah sorry about that. That's because I still haven't updated this tutorial to address webpack v2.

I actually have started work on it due to this issue https://github.com/AriaFallah/WebpackTutorial/issues/43, and I'm hoping to have it out in a week or so.

**Comment by wkoutre** [comment]
No problem at all.
