### ISSUE TITLE
Example package.json generates error on Win10 

### ISSUE THREAD

**Issue by joeycato** [AriaFallah/WebpackTutorial#9]
Great tutorial! Just wanted to let you know, when I attempted to execute the "npm run build" step, I received this error:

**package.json must be actual JSON, not just JavaScript.**

Removing the unnecessary comments from the package.json file was enough to fix it.

Thanks,
Joey

**Comment by AriaFallah** [comment]
Oh yeah sorry about that. I put in the comments in there for clarity's sake. I'll try to keep them outside in the future.
